### ISSUE TITLE
Reuse of npm hashlink package for IETF hashlink RFC?

### ISSUE THREAD

**Issue by msporny** [dlevs/hashlink#1]
Hi @dlevs, (cc: @dlongley, @davidlehn)

My name is Manu Sporny and I'm the RFC Editor for the Hashlink specification:

https://tools.ietf.org/html/draft-sporny-hashlink-03

This specification is used by a variety of IETF and W3C specifications, including but not limited to: Verifiable Credentials, Decentralized Identifiers, Web Ledger, and other systems that depend on content addressed identifiers.

We noticed that you're the package maintainer for the following npm repository, which hasn't had an update in quite some time:

https://www.npmjs.com/package/hashlink

Would it be possible for us to re-use your package to publish the reference library for the hashlink specification? We would, of course, credit you in the specification and the package for donating the package name to the international standardization effort.

What do you think?

**Comment by dlevs** [comment]
Hi Manu,

That's fine with me.

How does the transfer process work with npm? I'm out of the country and without access to a computer for the next couple of weeks, but if I can transfer control of that package to you via my phone, then I'm happy to help!

Cheers,
Dan

On 4 Aug 2019 04:28, Manu Sporny <notifications@github.com> wrote:

Hi @dlevs<https://github.com/dlevs>, (cc: @dlongley<https://github.com/dlongley>, @davidlehn<https://github.com/davidlehn>)

My name is Manu Sporny and I'm the RFC Editor for the Hashlink specification:

https://tools.ietf.org/html/draft-sporny-hashlink-03

This specification is used by a variety of IETF and W3C specifications, including but not limited to: Verifiable Credentials, Decentralized Identifiers, Web Ledger, and other systems that depend on content addressed identifiers.

We noticed that you're the package maintainer for the following npm repository, which hasn't had an update in quite some time:

https://www.npmjs.com/package/hashlink

Would it be possible for us to re-use your package to publish the reference library for the hashlink specification? We would, of course, credit you in the specification and the package for donating the package name to the international standardization effort.

What do you think?

**Comment by msporny** [comment]
@dlevs wrote:
> That's fine with me. How does the transfer process work with npm?

Wonderful, thank you Dan! 

All you have to do is add `dlongley`, `davidlehn`, and `msporny` as package maintainers for the npm package. To do that, go here:

https://www.npmjs.com/package/hashlink/access

... and then invite us. I think that's all that's required.

**Comment by dlevs** [comment]
No worries, I've added you all. I've left myself as admin just until you confirm that you have access. Feel free to remove me.
